# https://software-download.microsoft.com/sg/Win10_2004_Korean_x64.iso?t=17b0d576-b972-4b2c-a5b6-29b71be4e132&e=1594973366&h=7449242db9806580cb8ec76fb34f88b6

---
apiVersion: apps/v1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: qemu-server
spec:
 
  replicas: 1
  selector:
    matchLabels:
      app: "qemu-server"
  template:
    metadata:
      labels:
        app: qemu-server
    spec:
      
      volumes:
      - name: task-pv-storage-ssd
        persistentVolumeClaim:
          claimName: host-pvc-ssd
          readOnly: false
      containers:
      - name: qemu
        image: khjde1207/qemu:latest
        
        tcpSocket:
        securityContext:
          privileged: true
   
        resources:
          limits:
            memory: "5000M"
            cpu: "1000m"
        ports:
        - containerPort: 5959
          protocol: TCP
          name: "spice"

        volumeMounts:
        - mountPath: "/data"
          name: task-pv-storage-ssd
          subPath: ".qemu/"
        
        env:
        - name: VM_DISK_IMAGE
          value: "/data/win10img"
        - name: VM_DISK_IMAGE_SIZE
          value: "50G"
        - name: VM_RAM 
          value: "4096"
        - name: ISO
          value: "test.iso"
        - name: SPICE_PASSWORD
          value: "testest"
---
apiVersion: v1
kind: Service
metadata:
  name: qemu-server-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5959
      targetPort: 5959
      name: qemu      


  selector:
    app: qemu-server
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: qemu-ingressroute 
  namespace: default
spec:
  routes:
  - match: Host(`xxx.khjde1207.com`) 
    kind: Rule
    services:
    - name: qemu-server-service
      port: 5959